### ISSUE TITLE
nexial.enableEmail unable to send mail - from latest nexial-core build

### ISSUE THREAD

**Issue by AutoFahad** [nexiality/nexial-core#2]
Please see logs. I am trying to use gmail smtp

 Unable to send out notification email: Couldn't connect to host, port: localhost, 25; timeout -1
com.sun.mail.util.MailConnectException: Couldn't connect to host, port: localhost, 25; timeout -1;
  nested exception is:
        java.net.ConnectException: Connection refused: connect
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2118)
        at com.sun.mail.smtp.SMTPTransport.protocolConnect(SMTPTransport.java:712)
        at javax.mail.Service.connect(Service.java:366)
        at javax.mail.Service.connect(Service.java:246)
        at javax.mail.Service.connect(Service.java:195)
        at org.nexial.commons.javamail.MailObjectSupport.newTransport(MailObjectSupport.java:179)
        at org.nexial.commons.javamail.MailObjectSupport.createTransport(MailObjectSupport.java:110)
        at org.nexial.core.reports.Mailer.sendResult(Mailer.java:61)
        at org.nexial.core.reports.MailNotifier.notify(MailNotifier.java:81)
        at org.nexial.core.Nexial.notifyCompletion(Nexial.java:859)
        at org.nexial.core.Nexial.onExecutionComplete(Nexial.java:698)
        at org.nexial.core.Nexial.execute(Nexial.java:634)
        at org.nexial.core.Nexial.main(Nexial.java:212)
Caused by: java.net.ConnectException: Connection refused: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at com.sun.mail.util.SocketFetcher.createSocket(SocketFetcher.java:331)
        at com.sun.mail.util.SocketFetcher.getSocket(SocketFetcher.java:238)
        at com.sun.mail.smtp.SMTPTransport.openServer(SMTPTransport.java:2084)
        ... 12 more
2018-05-03 22:22:11,476 >> Exiting Nexial...
2018-05-03 22:22:11,476 >> shutdown starts...
2018-05-03 22:22:12,206 >> shutdown ends...

**Comment by mikeliucc** [comment]
Please see documentation about Gmail here:  https://nexiality.github.io/documentation/commands/mail/index#gmail

If the provided instruction suffice, please kindly close this ticket.  Thanks!

**Comment by mikeliucc** [comment]
Also, please have a read at this: https://nexiality.github.io/documentation/systemvars/index.html#nexial.enableEmail

You can set up your mail server connectivity via command line (as in `set JAVA_OPT=-D...`) or [project.properties](https://nexiality.github.io/documentation/userguide/UnderstandingProjectStructure.html).  It's pretty much a one-time set up.  Once you got it, you should be good to go.

**Comment by mikeliucc** [comment]
Here's some examples on how to set up gmail for nexial email notification.

#### Via Command Line
(on *NIX):
`export JAVA_OPT="-Dnexial.enableEmail=true -Dmail.smtp.host=smtp.gmail.com -Dmail.smtp.port=587 -Dmail.smtp.from=nexial-noreply@gmail.com -Dmail.smtp.auth=true -Dmail.smtp.username=<mail_account>@gmail.com -Dmail.smtp.password=<password> -Dmail.smtp.starttls.enable=true -Dnexial.scope.mailTo=<recipients>"`

(on Windows):
`set JAVA_OPT=-Dnexial.enableEmail=true -Dmail.smtp.host=smtp.gmail.com -Dmail.smtp.port=587 -Dmail.smtp.from=nexial-noreply@gmail.com -Dmail.smtp.auth=true -Dmail.smtp.username=<mail_account>@gmail.com -Dmail.smtp.password=<password> -Dmail.smtp.starttls.enable=true -Dnexial.scope.mailTo=<recipients>`

### Via project.properties
```text
nexial.enableEmail=true
nexial.scope.mailTo=<recipients>

mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.from=nexial-noreply@gmail.com
mail.smtp.auth=true
mail.smtp.username=<mail_account>@gmail.com
mail.smtp.password=<password>
mail.smtp.starttls.enable=true
```

Key things to note:
- Nexial will not send out email notification UNLESS `nexial.enableEmail` set to `true` and `nexial.scope.mailTo` properly configured to the intended recipients.
- For Gmail, `mail.smtp.starttls.enable` should be set to `true`.
- It is possible to put some settings via command line, some via project.properties, and even some in data file.  However, keeping things on track might get a little tricky.

**Comment by mikeliucc** [comment]
just realized that v1.1 has a restriction such that only the "command line" technique works... This will be fixed shortly.

**Comment by AutoFahad** [comment]
Thanks Mike! Works with new build! 
Go Nexial ! ! !
